### PR TITLE
Pre footer section

### PR DESCRIPTION
**Pull request by jaynaxissa**
## Context

https://ywgc.atlassian.net/browse/YWGC-36?atlOrigin=eyJpIjoiODIyYWJmM2Q4ZjM3NDdlM2JhYmU5MTFjOWE2OWU2M2QiLCJwIjoiaiJ9

## Work done
Add pre-footer section

## Manual testing instructions
- Pre-footer section should being showing.
- Pre-footer section should change into a different design when it's mobile.
- The fonts are different to web and mobile screen size and so is the text alignment.

## Note
- I have not apply the font to this new section as I'm not sure about it yet.
- Issue: for the web screen I noticed the space-between is making the space in the middle really sparse out, the bigger the screen is. Let me know if this is acceptable or whether it needs to be changed. Also when the screen is between mobile and medium web-screen the layout looks a bit weird as it collided onto each other quite a bit. Shall we fix this too or leave it like that?

### CODE REVIEW

**Review by ajkarczewski — APPROVED** [review]
nice job! thanks 😎

**Comment by alliequintano** [comment]
On mobile, it looks like the Yorkshire Wood Ground Crew title is wrapping the text more than we would expect at this width for example:
image

We took a look at seems like there is some extra padding here that can be removed:
image

**Comment by jaynaxissa** [comment]
> On mobile, it looks like the Yorkshire Wood Ground Crew title is wrapping the text more than we would expect at this width for example: image
> 
> We took a look at seems like there is some extra padding here that can be removed: image

Hey I added the padding because I wasn't sure how to make it looks like the design on figma. As the word "Crew" is in another line. Is there a different ways to do that rather than using padding?

**Comment by jaynaxissa** [comment]
@alliequintano

**Comment by alliequintano** [comment]
> > On mobile, it looks like the Yorkshire Wood Ground Crew title is wrapping the text more than we would expect at this width for example: image
> > 
> > We took a look at seems like there is some extra padding here that can be removed: image
> 
> Hey I added the padding because I wasn't sure how to make it looks like the design on figma. As the word "Crew" is in another line. Is there a different ways to do that rather than using padding?

I see! So we chatted about this a bit after you left, and what the figma is conveying is that the text wraps on smaller screens.

**Comment by cherry-pire** [comment]
Disregard the link in "Context." https://ywgc.atlassian.net/browse/YWGC-42?atlOrigin=eyJpIjoiMWQyYjcxMmU3ZmEwNDNjYTllOWY5NThmNzM2ZGVlNmYiLCJwIjoiaiJ9

**Pull request merged**
